Repository insightsengineering/teal.modules.general, pull requests merged in 2022-07, with the labels that each got.

#422 add reporter to modules
  DESCRIPTION
  NEWS.md
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_file_viewer.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
  R/tm_variable_browser.R
  man/tm_a_pca.Rd
  man/tm_a_regression.Rd
  man/tm_data_table.Rd
  man/tm_file_viewer.Rd
  man/tm_front_page.Rd
  man/tm_g_association.Rd
  man/tm_g_bivariate.Rd
  man/tm_g_distribution.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_g_scatterplotmatrix.Rd
  man/tm_missing_data.Rd
  man/tm_outliers.Rd
  man/tm_t_crosstable.Rd
  man/tm_variable_browser.Rd
  staged_dependencies.yaml
  vignettes/teal-modules-general.Rmd
Labels: core

#427 update desc file
  DESCRIPTION
Labels: core

#428 416 Implement `nestcolor` in TMG
  DESCRIPTION
  NEWS.md
  R/tm_a_pca.R
  R/tm_g_association.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_missing_data.R
  man/tm_a_pca.Rd
  man/tm_g_association.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_missing_data.Rd
  staged_dependencies.yaml
Labels: core, sme

#433 Update font awesome icon labels for FA 6
  R/tm_a_regression.R
  R/tm_g_distribution.R
  R/tm_missing_data.R
  R/tm_variable_browser.R
  R/utils.R
Labels: refactor

#431 remove filtered
  R/tm_missing_data.R
  R/tm_outliers.R
Labels: core

#430 reporter cleaning
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
  R/tm_variable_browser.R
Labels: core

#432 tmg css
  R/tm_data_table.R
  R/tm_file_viewer.R
  R/tm_front_page.R
  R/tm_g_scatterplot.R
  R/tm_missing_data.R
  R/tm_variable_browser.R
  R/utils.R
  inst/css/custom.css
  man/include_css_files.Rd
Labels: core
