Repository insightsengineering/teal.modules.general, pull requests merged in 2022-10, with the labels that each got.

#472 Update tm_g_distribution.R
  R/tm_g_distribution.R
Labels: core

#473 tm_missing_data: add dataname to report
  R/tm_missing_data.R
Labels: core

#475 allow easy close for front page module
  R/tm_front_page.R
Labels: core

#474 NEWS
  NEWS.md
Labels: core

#479 Update tm_missing_data.R
  NEWS.md
  R/tm_missing_data.R
Labels: bug, core

#483 scda.2022
  DESCRIPTION
  NEWS.md
  staged_dependencies.yaml
Labels: core, blocked, sme

#465 qenv warnings
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_data_table.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
Labels: core
