Repository insightsengineering/teal.modules.general, pull requests merged in 2023-08, with the labels that each got.

#541 propagate argument name change in teal::module
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_data_table.R
  R/tm_file_viewer.R
  R/tm_front_page.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
  R/tm_variable_browser.R
Labels: core

#553 Revert square bracket@main
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_missing_data.R
  R/tm_outliers.R
Labels: core

#555 [Bug]: plots from tm_g_scatterplot and tm_a_regression modules print on IDE 554
  R/tm_a_regression.R
  R/tm_g_scatterplot.R
Labels: core

#549 545 Keep selected variable in var browser as filters are changed
  NEWS.md
  R/tm_variable_browser.R
  man/render_tab_table.Rd
Labels: core

#562 561 Allow the selection of a categorical variable in `tm_outliers`
  R/tm_outliers.R
Labels: bug, core

#563 559 Change order of `Show R code`/`Show warnings` buttons to be consistent with other modules
  R/tm_g_bivariate.R
Labels: enhancement, core

#572 570 horizontal lines
  R/tm_a_pca.R
Labels: core

#573 Fixing inconsistent Styling and Layout for 'Show Warning' and 'Show R Code' Buttons
  R/tm_missing_data.R
  R/tm_t_crosstable.R
Labels: core

#565 Unified Visual Consistency for UI Components#564
  R/tm_variable_browser.R
Labels: core

#574 Add tables to `show-r-code` in distribution, scatterplot and outliers modules
  R/tm_g_distribution.R
  R/tm_g_scatterplot.R
  R/tm_outliers.R
Labels: bug, core

#581 566 Consistent white background for modules
  R/tm_data_table.R
  R/tm_g_distribution.R
Labels: core

#580 556 Longer labels for x axis in the `tm_variable_browser()` are not fully displayed
  R/tm_variable_browser.R
  man/plot_var_summary.Rd
Labels: core
