Repository insightsengineering/teal.modules.general, pull requests merged in 2024-02, with the labels that each got.

#630 Fix pkgdown redirect
  DESCRIPTION
  inst/WORDLIST
  man/teal.modules.general.Rd
  man/tm_a_pca.Rd
  man/tm_a_regression.Rd
  man/tm_data_table.Rd
  man/tm_file_viewer.Rd
  man/tm_front_page.Rd
  man/tm_g_association.Rd
  man/tm_g_bivariate.Rd
  man/tm_g_distribution.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_g_scatterplotmatrix.Rd
  man/tm_missing_data.Rd
  man/tm_outliers.Rd
  man/tm_t_crosstable.Rd
  man/tm_variable_browser.Rd
Labels: bug, core

#636 635 remove test theme
  R/teal.modules.general.R
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_data_table.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
  R/tm_variable_browser.R
  R/utils.R
  R/zzz.R
  data-raw/data.R
  man/shared_params.Rd
  man/tm_a_pca.Rd
  man/tm_a_regression.Rd
  man/tm_g_association.Rd
  man/tm_g_bivariate.Rd
  man/tm_g_distribution.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_missing_data.Rd
  man/tm_outliers.Rd
Labels: core

#638 fix nolint syntax
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
  R/tm_variable_browser.R
  data-raw/data.R
Labels: core

#659 642 unused functions
  R/tm_g_bivariate.R
  R/tm_variable_browser.R
  R/utils.R
  man/extract_input.Rd
Labels: core

#670 Adds common `@return` for modules and corrects linting
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
  R/utils.R
  man/shared_params.Rd
Labels: core

#651 29 add non-cdisc examples to the modules
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_data_table.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
  R/tm_variable_browser.R
  man/tm_a_pca.Rd
  man/tm_a_regression.Rd
  man/tm_data_table.Rd
  man/tm_g_association.Rd
  man/tm_g_bivariate.Rd
  man/tm_g_distribution.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_g_scatterplotmatrix.Rd
  man/tm_missing_data.Rd
  man/tm_outliers.Rd
  man/tm_t_crosstable.Rd
  man/tm_variable_browser.Rd
Labels: core

#663 643 potential removal of dependencies
  .pre-commit-config.yaml
  DESCRIPTION
  NAMESPACE
  R/teal.modules.general.R
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_data_table.R
  R/tm_front_page.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_missing_data.R
  man/tm_a_pca.Rd
  man/tm_a_regression.Rd
  man/tm_data_table.Rd
  man/tm_front_page.Rd
  man/tm_g_association.Rd
  man/tm_g_bivariate.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_missing_data.Rd
Labels: core

#672 missed commit in #663
  DESCRIPTION
Labels: core

#673 658 remove var labels@pre release@main
  R/tm_a_pca.R
  R/tm_missing_data.R
  R/tm_variable_browser.R
  R/utils.R
  man/var_labels.Rd
Labels: core

#679 docs: update the vignette author to "NEST CoreDev"
  vignettes/teal-modules-general.Rmd
  vignettes/using-association-plot.Rmd
  vignettes/using-bivariate-plot.Rmd
  vignettes/using-cross-table.Rmd
  vignettes/using-data-table.Rmd
  vignettes/using-outliers-module.Rmd
  vignettes/using-regression-plots.Rmd
  vignettes/using-response-plot.Rmd
  vignettes/using-scatterplot-matrix.Rmd
  vignettes/using-scatterplot.Rmd
Labels: documentation, core

#652 pre-release `tm_variable_browser` document update
  R/tm_variable_browser.R
  man/create_sparklines.Rd
  man/tm_variable_browser.Rd
  man/validate_input.Rd
  man/var_missings_info.Rd
Labels: core

#666 pre-release `tm_g_response` document update
  R/tm_g_response.R
  man/tm_g_response.Rd
Labels: core

#664 pre-release `tm_t_crosstable` document update
  R/tm_t_crosstable.R
  man/tm_t_crosstable.Rd
Labels: core

#646 pre-release `tm_a_pca` document update
  R/tm_a_pca.R
  man/tm_a_pca.Rd
Labels: core

#653 pre-release `tm_outliers` document update
  R/tm_outliers.R
  man/tm_outliers.Rd
Labels: core

#654 pre-release `tm_front_page` document update
  R/tm_front_page.R
  man/tm_front_page.Rd
Labels: core

#657 pre-release `tm_g_scatterplot` document update
  R/tm_g_scatterplot.R
  man/tm_g_scatterplot.Rd
Labels: core

#667 pre-release ` tm_data_table` document update
  R/tm_data_table.R
  man/tm_data_table.Rd
Labels: core

#676 pre-release other utils functions document update
  R/data.R
  R/teal.modules.general.R
  R/utils.R
  man/add_facet_labels.Rd
  man/call_fun_dots.Rd
  man/include_css_files.Rd
  man/is_tab_active_js.Rd
  man/rADTTE.Rd
  man/shared_params.Rd
  man/teal.modules.general.Rd
  man/tm_a_pca.Rd
  man/tm_a_regression.Rd
  man/tm_data_table.Rd
  man/tm_g_association.Rd
  man/tm_g_bivariate.Rd
  man/tm_g_distribution.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_g_scatterplotmatrix.Rd
  man/tm_missing_data.Rd
  man/tm_outliers.Rd
  man/tm_t_crosstable.Rd
  man/tm_variable_browser.Rd
  man/variable_type_icons.Rd
  man/varname_w_label.Rd
Labels: core

#668 pre-release `tm_missing_data` document update
  R/tm_missing_data.R
  man/tm_missing_data.Rd
Labels: core

#661 pre-release `tm_g_scatterplotmatrix` document update
  R/tm_g_scatterplotmatrix.R
  man/get_scatterplotmatrix_stats.Rd
  man/tm_g_scatterplotmatrix.Rd
Labels: core

#683 pre-release: Update verdpecheck and pre-commit
  .pre-commit-config.yaml
  DESCRIPTION
Labels: core

#687 Vignette changes
  .lintr
  R/tm_g_response.R
  vignettes/images/app-teal-modules-general.png
  vignettes/images/app-using-association-plot.png
  vignettes/images/app-using-bivariate-plot.png
  vignettes/images/app-using-cross-table.png
  vignettes/images/app-using-data-table.png
  vignettes/images/app-using-outliers-module.png
  vignettes/images/app-using-regression-plots.png
  vignettes/images/app-using-response-plot.png
  vignettes/images/app-using-scatterplot-matrix.png
  vignettes/images/app-using-scatterplot.png
  vignettes/teal-modules-general.Rmd
  vignettes/using-association-plot.Rmd
  vignettes/using-bivariate-plot.Rmd
  vignettes/using-cross-table.Rmd
  vignettes/using-data-table.Rmd
  vignettes/using-outliers-module.Rmd
  vignettes/using-regression-plots.Rmd
  vignettes/using-response-plot.Rmd
  vignettes/using-scatterplot-matrix.Rmd
  vignettes/using-scatterplot.Rmd
Labels: documentation, core

#656 pre-release `tm_g_association` document update
  R/tm_g_association.R
  man/tm_g_association.Rd
Labels: core

#669 pre-release `tm_g_distribution` document update
  R/tm_g_distribution.R
  man/tm_g_distribution.Rd
Labels: core

#655 pre-release `tm_a_regression` document update
  R/tm_a_regression.R
  man/tm_a_regression.Rd
Labels: core

#688 Fix the silent error in `tm_a_pca`
  R/tm_a_pca.R
Labels: bug, core

#690 Remove the internal function `var_labels` in favour of `teal.data::col_labels`
  R/tm_missing_data.R
  R/tm_variable_browser.R
  R/utils.R
  man/var_labels.Rd
Labels: core

#675 `tm_g_regression` labels are no longer allowed out of bounds
  .pre-commit-config.yaml
  DESCRIPTION
  NEWS.md
  R/tm_a_regression.R
  inst/WORDLIST
  man/tm_a_regression.Rd
Labels: core

#691 Standardise function titles similar to what we have in tmc
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_data_table.R
  R/tm_file_viewer.R
  R/tm_front_page.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_response.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/tm_t_crosstable.R
  R/tm_variable_browser.R
  R/utils.R
  man/shared_params.Rd
  man/tm_a_pca.Rd
  man/tm_a_regression.Rd
  man/tm_data_table.Rd
  man/tm_file_viewer.Rd
  man/tm_front_page.Rd
  man/tm_g_association.Rd
  man/tm_g_bivariate.Rd
  man/tm_g_distribution.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_g_scatterplotmatrix.Rd
  man/tm_missing_data.Rd
  man/tm_outliers.Rd
  man/tm_t_crosstable.Rd
  man/tm_variable_browser.Rd
Labels: documentation, core

#681 pre-release vignettes review
  .lintr
  R/tm_g_response.R
  vignettes/images/app-teal-modules-general.png
  vignettes/images/app-using-association-plot.png
  vignettes/images/app-using-bivariate-plot.png
  vignettes/images/app-using-cross-table.png
  vignettes/images/app-using-data-table.png
  vignettes/images/app-using-outliers-module.png
  vignettes/images/app-using-regression-plots.png
  vignettes/images/app-using-response-plot.png
  vignettes/images/app-using-scatterplot-matrix.png
  vignettes/images/app-using-scatterplot.png
  vignettes/teal-modules-general.Rmd
  vignettes/using-association-plot.Rmd
  vignettes/using-bivariate-plot.Rmd
  vignettes/using-cross-table.Rmd
  vignettes/using-data-table.Rmd
  vignettes/using-outliers-module.Rmd
  vignettes/using-regression-plots.Rmd
  vignettes/using-response-plot.Rmd
  vignettes/using-scatterplot-matrix.Rmd
  vignettes/using-scatterplot.Rmd
Labels: core

#680 641 non exported functions
  R/tm_file_viewer.R
  R/tm_front_page.R
  R/tm_g_bivariate.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_variable_browser.R
  R/utils.R
  R/zzz.R
  man/call_fun_dots.Rd
  man/create_sparklines.Rd
  man/plot_var_summary.Rd
  man/tm_file_viewer.Rd
  man/tm_front_page.Rd
  man/tm_g_bivariate.Rd
  man/tm_missing_data.Rd
  man/var_missings_info.Rd
  man/var_summary_table.Rd
  man/variable_type_icons.Rd
  man/varname_w_label.Rd
Labels: core

#692 Fix factors crash in `tm_g_association`
  R/tm_g_association.R
  R/tm_g_bivariate.R
Labels: bug, core

#699 Store the user selections so our default selection logic can be applied
  R/tm_variable_browser.R
Labels: bug, core

#698 standardize the notation for optional parameters
  R/tm_a_pca.R
  R/tm_a_regression.R
  R/tm_g_association.R
  R/tm_g_bivariate.R
  R/tm_g_distribution.R
  R/tm_g_scatterplot.R
  R/tm_g_scatterplotmatrix.R
  R/tm_missing_data.R
  R/tm_outliers.R
  R/utils.R
  man-roxygen/ggplot2_args_multi.R
  man/get_scatterplotmatrix_stats.Rd
  man/include_css_files.Rd
  man/roxygen/templates/ggplot2_args_multi.R
  man/shared_params.Rd
  man/tm_a_pca.Rd
  man/tm_a_regression.Rd
  man/tm_data_table.Rd
  man/tm_g_association.Rd
  man/tm_g_bivariate.Rd
  man/tm_g_distribution.Rd
  man/tm_g_response.Rd
  man/tm_g_scatterplot.Rd
  man/tm_g_scatterplotmatrix.Rd
  man/tm_missing_data.Rd
  man/tm_outliers.Rd
  man/tm_t_crosstable.Rd
  man/tm_variable_browser.Rd
Labels: core
